# Generated by Django 2.2.2 on 2019-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_heading', models.CharField(max_length=50)),
                ('event_details', models.CharField(max_length=500)),
                ('event_date', models.DateField(verbose_name='event date')),
            ],
        ),
    ]
