# Generated by Django 2.2.2 on 2019-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(default='db_images/no-photo.jpg', upload_to='db_images/'),
        ),
    ]
