# Generated by Django 2.2.2 on 2019-06-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(default=None, upload_to='gallery/'),
        ),
    ]
