# Generated by Django 2.2.2 on 2019-06-25 10:08

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190625_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=stdimage.models.StdImageField(blank=True, upload_to='gallery/new'),
        ),
    ]
