# Generated by Django 2.2.2 on 2019-07-01 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190701_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
