# Generated by Django 2.2.2 on 2019-07-01 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_event_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
